Add ! icon to stderr process logs, decrease size of container icon
oslabs-beta/DockerPulse pull request #31
Opened 2023-06-24 22:19 UTC by davidchuang5

### Overview

- Red ! icon present next to all stderr logs
- Container icon size decreased
- Typography code for logs made more DRY
 
### Before
<img width="1317" alt="Screenshot 2023-06-24 at 12 02 18 PM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/d55a59a3-23f9-4696-a173-d77d0f316a21">

### After
<img width="1082" alt="Screenshot 2023-06-24 at 5 18 55 PM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/1a7e2430-f59d-4349-ad30-10a0bc794f7d">

2023-06-25 23:03 UTC, scotthallock commented
Can we make the `ErrorRounded` Icon center-aligned so that it is visually aligned with the other table elements?

Also, there should be a gap between the icon and the text, identical to the gap between the `ContainerIcon` and the container name.

![Screenshot 2023-06-24 at 12 16 01 PM](https://github.com/oslabs-beta/DockerPulse/assets/121207468/f2843953-38f4-4fac-93a3-91f9c39035e4)

2023-06-25 23:05 UTC, scotthallock requested changes

2023-06-25 23:06 UTC, scotthallock commented on ui/src/pages/Logs/Logs.tsx
> +
Delete this added line

2023-06-26 01:51 UTC, scotthallock approved these changes

2023-06-26 04:17 UTC, patrickv77 approved these changes
Great catch on the spacing Scott and awesome job with the fixes David. Looks amazing now.

2023-06-26 15:05 UTC, leejun07 approved these changes

2023-06-26 15:08 UTC, merged