added drawer to logsPage, created logsfile folder, added logs.tsx and…
oslabs-beta/DockerPulse pull request #5
Opened 2023-06-14 01:48 UTC by davidchuang5

… css file to logsfile folder

2023-06-14 04:01 UTC, scotthallock requested changes

2023-06-14 04:01 UTC, scotthallock commented on ui/src/pages/Logfiles/Logs.tsx
> +  function valuetext(value: number) {
What is the purpose of this function?

2023-06-14 04:02 UTC, scotthallock commented
For future PRs it would be nice if you added a screenshot of the UI to the PR description, that way we can easily see what was added.

2023-06-14 16:05 UTC, davidchuang5 commented on ui/src/pages/Logfiles/Logs.tsx
> +      <div className="parentDiv">
Still using the custom CSS only for the sake of positioning the drawer to the left of the logs display

2023-06-14 16:13 UTC, davidchuang5 commented on ui/src/pages/Logfiles/Logs.tsx
> +  function valuetext(value: number) {
Displays the time on the slider

2023-06-14 16:17 UTC, davidchuang5 commented
<img width="1246" alt="Screenshot 2023-06-14 at 11 16 55 AM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/7d08bbcd-b1d6-4811-beed-a13d7d5e18a1">
<img width="1223" alt="Screenshot 2023-06-14 at 11 16 38 AM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/15070557-d440-491a-ab23-e6099643d5e3">

2023-06-15 15:24 UTC, leejun07 approved these changes

2023-06-16 00:56 UTC, davidchuang5 commented
<img width="1275" alt="Screenshot 2023-06-15 at 7 56 26 PM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/0e8f3866-965d-4fd2-87ec-098d2abac44f">

2023-06-16 00:57 UTC, davidchuang5 commented
<img width="1265" alt="Screenshot 2023-06-15 at 7 56 53 PM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/d8419872-6f38-49c7-9102-221100b261e6">

2023-06-16 15:20 UTC, davidchuang5 commented
<img width="1262" alt="Screenshot 2023-06-16 at 10 20 08 AM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/f2244358-115b-43e4-bf19-6156bd943a44">
<img width="1265" alt="Screenshot 2023-06-16 at 10 20 25 AM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/8a121195-da16-4657-95ee-5185c086c376">

2023-06-16 15:25 UTC, scotthallock commented
@davidchuang5 an earlier PR you made added a `package-lock.json` file to the root directory, but the root direction should not have a `package.json` or a `package-lock.json`. (Only the `/ui` and `/backend` folders need package.json because they are npm projects).

Can you remove these files from the root directory?

2023-06-16 15:28 UTC, davidchuang5 commented
<img width="1266" alt="Screenshot 2023-06-16 at 10 28 22 AM" src="https://github.com/oslabs-beta/DockerPulse/assets/110566167/d3109c4f-7e4c-4858-aac3-5b5eda8f25c6">

2023-06-17 01:02 UTC, scotthallock approved these changes
LGTM

2023-06-17 02:10 UTC, merged